export const ukCities = [
  "Bath",
  "Birmingham",
  "Bradford",
  "Brighton and Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Carlisle",
  "Chester",
  "Chelmsford",
  "Chichester",
  "Colchester",
  "Coventry",
  "Derby",
  "Doncaster",
  "Durham",
  "Ely",
  "Exeter",
  "Gloucester",
  "Hereford",
  "Kingston upon Hull",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Lichfield",
  "Lincoln",
  "Liverpool",
  "London",
  "Manchester",
  "Milton Keynes",
  "Newcastle upon Tyne",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Ripon",
  "Salford",
  "Salisbury",
  "Sheffield",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "Stoke-on-Trent",
  "Sunderland",
  "Truro",
  "Wakefield",
  "Wells",
  "Westminster",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "York",

  "Aberdeen",
  "Dundee",
  "Dunfermline",
  "Edinburgh",
  "Glasgow",
  "Inverness",
  "Perth",
  "Stirling",

  "Bangor",
  "Cardiff",
  "Newport",
  "St Asaph",
  "St Davids",
  "Swansea",
  "Wrexham",

  "Armagh",
  "Belfast",
  "Derry",
  "Lisburn",
  "Newry",
  "Bangor",
];

console.log(`Total Number of the Cities: ${ukCities.length}`);
